version: '3.4'
services:
  metad0:
    image: vesoft/nebula-metad:v3.1.0
    environment:
      USER: root
      TZ: UTC
    volumes:
      - ./data/meta0:/data/meta
    networks:
      - nebula-net
    ports:
      - 9559:9559
    restart: on-failure

  storaged0:
    image: vesoft/nebula-storaged:v3.1.0
    environment:
      USER: root
      TZ: UTC
    volumes:
      - ./data/storage0:/data/storage
    networks:
      - nebula-net
    ports:
      - 9779:9779
    restart: on-failure

  graphd:
    image: vesoft/nebula-graphd:v3.1.0
    environment:
      USER: root
      TZ: UTC
    networks:
      - nebula-net
    ports:
      - 9669:9669
      - 19669:19669
      - 19670:19670
    restart: on-failure

  nebula-graph-studio:
    image: vesoft/nebula-graph-studio:v3.5.0
    environment:
      USER_PASSWD: "true"  # Enables password protection for the Studio login
    ports:
      - 7001:7001  # Exposes Nebula Graph Studio on port 7001
    networks:
      - nebula-net
    depends_on:
      - graphd  # Ensures that graphd service is up before starting Studio
    restart: on-failure

networks:
  nebula-net:
